services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-test
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
    environment:
      - LLM_MODEL_VERSION=${LLM_MODEL_VERSION}
    entrypoint: ["/bin/bash", "/ollama_entrypoint.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep 'ollama serve' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 180s  # 3 minuti per il download del modello
      
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui-test
    ports:
      - "${WEBUI_PORT}:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    container_name: open-webui-nginx-test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - open-webui
    restart: unless-stopped
    
volumes:
  ollama_data:
  open_webui_data:
